import convertTextToMatrix from '../../utils/convertTextToMatrix';

const fireshipText = `....O..O....
....O..O....
...O....O...
...O....O...
...O....O...
...O....O...
..OOO..OOO..
..O.OOOO.O..
...O....O...
............
............
.....OO.....
.....OO.....
.....OO.....
...O....O...
.OOO....OOO.
OOO......OOO
OO........OO
.OOOOOOOOOO.
..OOOOOOOO..
....OOOO....`;

const fireship = convertTextToMatrix(fireshipText);

export default fireship;
